export const ReactQueryKeys = {
	server: 'server',
	serverCurrentUsage: 'serverCurrentUsage',
	serverMainInfo: 'serverMainInfo',
	serverConsole: 'serverConsole',
	serverActivePlayers: 'serverActivePlayers',
	serverBackups: 'serverBackups',
	serverSettings: 'serverSettings',
	serverFiles: 'serverFiles',
	serverFileContent: 'serverFileContent',
	userServers: 'userServers',
	publicServers: 'publicServers',
	mods: 'mods',
	mod: 'mod',
	modDescription: 'modDescription',
	searchMods: 'searchMods',
	modsCompilation: 'modsCompilation',
	modsGroupedCategories: 'modsGroupedCategories',
	modsCategories: 'modsCategories',
	modsGameVersions: 'modsGameVersions',
	whiteList: 'whiteList',
	operators: 'operators',
	bannedIps: 'bannedIps',
	bannedPlayers: 'bannedPlayers',
}
